### ISSUE TITLE
't leaders' didn't work

### ISSUE THREAD

**Issue by p45** [sferik/t#281]
Hi guys..

I have a problem with my "t leaders" command . When I type "t leaders", this report shows up:

 /var/lib/gems/1.9.1/gems/t-2.9.0/lib/t/printable.rb:202:in `print_users': undefined method `sort_by' for nil:NilClass (NoMethodError)
	from /var/lib/gems/1.9.1/gems/t-2.9.0/lib/t/cli.rb:481:in `leaders'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/1.9.1/gems/t-2.9.0/bin/t:20:in `<top (required)>'
	from /usr/local/bin/t:23:in `load'
	from /usr/local/bin/t:23:in `<main>'

Oya, as far as I know, this is the only command I cannot run. The other works perfectly.

Thanks :)

**Comment by sferik** [comment]
Thanks for reporting this issue. It turned out to be a bug in the `twitter` gem, which I also maintain, and [just patched](https://github.com/sferik/twitter/commit/e22a5601ec702632510b3e983e50929ceb334b95). It’s times like these when I wish Ruby had a static type checker.

If you type `gem update twitter`, that should fix the problem.

**Comment by p45** [comment]
Thank you Sferik :)

Oya, have I told you that 't' is a great twitter client.
