### ISSUE TITLE
Feature: `t schedule` and `t auto` to schedule and auto-publish tweets

### ISSUE THREAD

**Issue by patmaddox** [sferik/t#299]
I propose two new commands: `schedule` and `auto`.

`t schedule "10 minutes from now" "this tweet is in the future"` - saves the tweet to a file with a timestamp, to be published in the future

`t auto` - looks at saved tweets for any timestamps in the past, publishes them, and deletes the file

*I'm posting this feature idea for early feedback, before implementing it myself*

**Comment by sferik** [comment]
I’m currently :-1: on this feature. Let me try to explain why…

`t` is designed to be a Unix utility, in an ecosystem of Unix utilities, that embraces the [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy#Doug_McIlroy_on_Unix_programming):

> Write programs that do one thing and do it well. Write programs to work together. Write programs to handle text streams, because that is a universal interface.

If you look at the [Usage Examples](https://github.com/sferik/t#usage-examples) in this repository’s `README`, many of them show `t` being used in concert with other Unix commands. For example:

#### Unfollow 10 people who haven't tweeted in the longest time
    t followings -l --sort=tweeted | head -10 | awk '{print $1}' | xargs t unfollow -i

Given the existence of `head`, `awk`, and `xargs`, I’d rather not duplicate this functionality in `t`. On the other hand, I have reimplemented some of the functionality in `sort` because it doesn’t work on timestamps in `%b %e %H:%M` format.

I believe the functionality you’re requesting can already be achieved by chaining a couple Unix commands together:

    (sleep 600 && t update "this tweet is in the future") &

Implementing this feature, as you’ve proposed it, would add a lot of complexity:

1. Parsing "10 minutes from now" into a valid timestamp.
2. Supporting multiple languages (e.g. "10 Minuten von jetzt").
3. Handling edge cases with timezones and daylight savings time (e.g. if someone schedules a tweet while on a plane and then lands in a different timezone).
4. A daemon running in the background, polling for unpublished tweets.
5. Avoiding race conditions in the case where multiple daemons are running.
6. Handling the case where a user changes their active Twitter account after scheduling a tweet.
7. Handling the case where a user deletes their active Twitter account after scheduling a tweet.

If something fails, how would you notify the user of the problem? Would you retry? If so, how often? What if you got stuck in a perpetual error loop?

All of these questions could be answered, but it doesn’t seem worth reinventing (and then maintaining) utilities like `sleep` and `cron`. If you don’t like `sleep` or `cron`, there are [various](https://github.com/tomykaira/clockwork) [alternatives](https://github.com/jmettraux/rufus-scheduler), which give you the kind of interface you’ve requested.

If you can provide an example use-case that can’t be handled by any of those utilities, that is somehow specific to the domain of Twitter, I will gladly reconsider this feature request. :smiley:

**Comment by patmaddox** [comment]
Good points. I didn't specify *how* I'd implement it, which is unfortunate, because I had written some scripts that use t :)

Here are the pieces:

* [scheduler](https://gist.github.com/patmaddox/4220d9b301b009aa69fb#file-1_schedule-rb)
* [auto-tweeter](https://gist.github.com/patmaddox/4220d9b301b009aa69fb#file-2_auto-rb)
* [crontab](https://gist.github.com/patmaddox/4220d9b301b009aa69fb#file-3_crontab)

I'll address your points as best I can.

1. [Chronic!](https://rubygems.org/gems/chronic) (I actually just started with Time.parse and normal times until I remembered chronic)
2. I don't know if chronic supports multiple languages. But I don't think it needs to. I started by using times like "8pm" which is handled by Time.parse (and chronic)
3. `Time#utc` covers that. So, `Chronic.parse('10 minutes from now').utc` compared to `Time.now.utc`.
4. No daemon. The auto-runner just looks for tweets that should be published. You can run it manually, or using `cron` like I do.
5. Definitely something to consider, even with cron in the picture.
6. The twitter account can be stored in the file name as well. So for example `1449336460_u123.tweet` corresponds to user w/ twitter user id (not handle) 123. Auto-scheduler can pass in the id(s) to filter on.
7. I'm punting on this :)  Deleting an account is pretty rare. Easy enough to track the error and add the id to a .t_ignored_ids file or something.

Failure is notified via `$stderr` so they get feedback on the command, or a log file if they pipe to it, or mail in the case of cron.

I definitely don't want to re-implement `sleep` and `cron`. I want something that works neatly with `sleep` and `cron`.

Let  me know if that gets you any closer to changing your mind... and if not, I'll just carry on :)

**Comment by patmaddox** [comment]
new proposal:

I'll implement this in a separate project (which I'll call `tauto` for now). If at any point you think it makes sense to bring it in to `t`, we can.

But I suspect you're right and we won't, and I'm fine with that.

**Comment by sferik** [comment]
I’m still not convinced this needs to be part of `t` or that it would add significant functionality that can’t be achieved with existing command-line utilities but please feel free to try and prove me wrong. If you release this as a separate project and it gets significant traction, I’ll gladly reconsider this decision.
